site_name: Cloud Security Blogs
theme:
  name: material
  custom_dir: overrides
  features:
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra_css:
  - custom.css
 
plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/naman-sogani-567033134/
  footnote: |
    The views and opinions expressed on this blog are solely my own and do not necessarily reflect the views or positions of my employer (PwC). All content is for informational purposes only and should not be considered professional advice. My employer does not endorse or approve the content of this blog. Views relating to my professional work are my own perspectives and do not reflect official positions or policies of my employer.
  copyright: ""
